name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix. os }}
    strategy:
      matrix:
        os: [ 'ubuntu-latest', 'macos-latest' ]
        go: [ '1.17.x', '1.16.x' ]
    name: "Test [ Go ${{ matrix.go }} on ${{ matrix.os }} ]"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Cache Go modules
        uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Install Go stable version
        if: matrix.go != 'tip'
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Install Go tip
        if: matrix.go == 'tip'
        run: |
          git clone --depth=1 https://go.googlesource.com/go $HOME/gotip
          cd $HOME/gotip/src
          ./make.bash
          echo "::set-env name=GOROOT::$HOME/gotip"
          echo "::add-path::$HOME/gotip/bin"
          echo "::add-path::$(go env GOPATH)/bin"
      - name: Test
        run: go test -v -race ./...
      - name: Upload code coverage to codecov
        if: matrix.go == '1.17.x'
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.out
 
